[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "alkahest-py"
version = "1.1.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
features = ["pyo3/extension-module"]
include = [
    { path = "alkahest_py/__init__.pyi", format = "wheel" },
    { path = "alkahest_py/alkahest_py.pyi", format = "wheel" },
    { path = "alkahest_py/py.typed", format = "wheel" },
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.24.0",
    "eth-account>=0.13.0",
]
