from __future__ import annotations

from typing import Any

PyAlkahestClient: Any
EnvTestManager: Any
PyMockERC20: Any
PyMockERC721: Any
PyMockERC1155: Any
PyWalletProvider: Any
PyERC20EscrowObligationData: Any
PyERC20PaymentObligationData: Any
PyERC721EscrowObligationData: Any
PyERC721PaymentObligationData: Any
PyERC1155EscrowObligationData: Any
PyERC1155PaymentObligationData: Any
PyNativeTokenEscrowObligationData: Any
PyNativeTokenPaymentObligationData: Any
PyTokenBundleEscrowObligationData: Any
PyTokenBundlePaymentObligationData: Any
PyAttestationEscrowObligationData: Any
PyAttestationReferenceEscrowObligationData: Any
HookBasedClient: Any
PyAmountHookData: Any
PyTokenIdHookData: Any
PyErc1155HookData: Any
PyNativeTokenHookData: Any
PyAttestationHookData: Any
PyAttestationReferenceHookData: Any
PyHookEscrowObligationData: Any
PyHooksEscrowObligationData: Any
SplittersClient: Any
PySplitterDemandData: Any
PyAmountSplit: Any
PyBundleSplit: Any
StringObligationClient: Any
PyStringObligationData: Any
CommitRevealObligationClient: Any
PyCommitRevealObligationData: Any
PyCommitRevealDemandData: Any
OracleClient: Any
PyOracleAddresses: Any
PyOracleAttestation: Any
PyDecision: Any
PyArbitrationMode: Any
ArbitersClient: Any
AllArbiter: Any
AnyArbiter: Any
AllArbiterDemandData: Any
AnyArbiterDemandData: Any
PyTrustedOracleArbiterDemandData: Any
PyCommitmentTrustedOracleArbiterDemandData: Any
ERC8004ArbiterDemandData: Any
AttesterArbiterDemandData: Any
RecipientArbiterDemandData: Any
SchemaArbiterDemandData: Any
UidArbiterDemandData: Any
RefUidArbiterDemandData: Any
RevocableArbiterDemandData: Any
TimeAfterArbiterDemandData: Any
TimeBeforeArbiterDemandData: Any
TimeEqualArbiterDemandData: Any
ExpirationTimeAfterArbiterDemandData: Any
ExpirationTimeBeforeArbiterDemandData: Any
ExpirationTimeEqualArbiterDemandData: Any
PyDecodedAllArbiterDemandData: Any
PyDecodedAnyArbiterDemandData: Any
PyDecodedDemand: Any
PyErc20Data: Any
PyErc20Addresses: Any
PyErc721Addresses: Any
PyErc1155Addresses: Any
PyNativeTokenAddresses: Any
PyTokenBundleAddresses: Any
PyHookBasedAddresses: Any
PySplittersAddresses: Any
PyAttestationAddresses: Any
PyStringObligationAddresses: Any
PyCommitRevealObligationAddresses: Any
PyArbitersAddresses: Any
PyDefaultExtensionConfig: Any
PyAttestation: Any
PyAttestationRequest: Any
PyAttestationRequestData: Any
PyAttested: Any
PyRevocationRequest: Any
PyRevocationRequestData: Any
PyRevoked: Any
PyTimestamped: Any
